### ISSUE TITLE
Message not received when broadcasted via go-libp2p-pubsub

### ISSUE THREAD

**Issue by iNDicat0r** [ChainSafe/js-libp2p-gossipsub#150]
Some nodes are implemented in golang using (go-libp2p-pubsub), but they never arrive using this js library. Is there any known issue ?

**Comment by vasco-santos** [comment]
They will be able to receive the messages, but it will depend on how your overlay network is defined.

You will need to be connected to a set of libp2p nodes sharing the same pubsub topic interests, in order to receive the message. How are you establishing your node connectivity and peer discover, and how will they discover go nodes? Moreover, are you using this on Node.js or browser node?

**Comment by iNDicat0r** [comment]
I connect them directly to each other using peerstore and dial and they still don't receive messages. I am using electron which is executed in context of nodejs.

**Comment by vasco-santos** [comment]
Can you provide us a test case for this? 
I locally tried go node with js node using gossipsub (directly connected), and after subscribing I could receive the messages as expected.

**Comment by jerradpatch** [comment]
I have this same issue, I cannot get the data to be received in a simple test

```typescript
import Gossipsub from 'libp2p-gossipsub';
import Libp2p from 'libp2p';

test('exact reporoduction of gossip', async (done)=>{
    const Gossipsub = require('libp2p-gossipsub');
    const options = {emitSelf: true, gossipIncoming: true};
    const node1= await createNodeExact();
    const node2 = await createNodeExact();
    // await node1.start();
    // await node2.start();

    const gsub1 = new Gossipsub(node1, options);
    const gsub2 = new Gossipsub(node2, options);

    await gsub1.start();
    await gsub2.start();

    gsub1.on('fruit', (data) => {
      console.log(data)
      done();
    });
    gsub1.subscribe('fruit');

    gsub2.publish('fruit', new TextEncoder().encode('banana'))
  }, 20e3);
  
  async function createNodeExact() {
    const transportKey = TCP.prototype[Symbol.toStringTag];
    const defaultConfig = {
      addresses: {
        listen: ['/ip4/0.0.0.0/tcp/0']
      },
      modules: {
        transport: [TCP],
        streamMuxer: [MPLEX],
        connEncryption: [NOISE],
        peerDiscovery: [MulticastDNS],
        pubsub: Gossipsub
      },
      config: {
        pubsub: {
          emitSelf: true,
          enabled: false
        },
        peerDiscovery: {
          autoDial: true,
          [MulticastDNS.tag]: {
            interval: 1000,
            enabled: true
          }
        },
        transport: {
          [transportKey]: {
            filter: filters.all
          }
        }
      }
    };

    return Libp2p.create(defaultConfig);
  }
  
  ```

**Comment by vasco-santos** [comment]
Hey @jerradpatch 

For your nodes to be able to properly exchange messages they need to be connected to a set of common peers (you can look into the spec: https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.0.md). If the peers are directly connected to each other, they will be able to to exchange pubsub messages without any problems, but if they are not they will need to have the minimum number of common connected peers to be able to exchange pubsub messages reliably. You can see the tests in https://github.com/ChainSafe/js-libp2p-gossipsub/blob/master/test/go-gossipsub.js for tests that create these connectivity scenarios, denseConnected and sparseConnect
