### ISSUE TITLE
Add time-cache typescript types

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/js-libp2p-gossipsub#152]
Currently, we have a `@ts-ignore` hiding the fact that `time-cache` has no types.
This causes type errors for downstream users that don't have the `time-cache` types accessible.

**Comment by 3xtr4t3rr3str14l** [comment]
unstale

**Comment by dapplion** [comment]
time-cache has show up in my profiles taking 3-5% of total CPU time

**Comment by dapplion** [comment]
No longer used:

https://github.com/ChainSafe/js-libp2p-gossipsub/blob/fe07f2039a6a3b844ec2b4f56ce18aa12bae6b21/ts/utils/time-cache.ts#L10-L15
