### ISSUE TITLE
Breaking change in v0.9.1

### ISSUE THREAD

**Issue by achingbrain** [ChainSafe/js-libp2p-gossipsub#154]
`0.9.1` bumped the `libp2p-interfaces` dep from `0.10.x` to `0.11.x`.  The current `libp2p` release depends on `0.10.x` so the types are incompatible.

Errors manifest as:

```
src/runtime/libp2p-nodejs.js(40,7): error TS2419: Types of construct signatures are incompatible.
  Type 'new (libp2p: Libp2p, options?: Partial<GossipInputOptions> | undefined) => Gossipsub' is not assignable to type 'new (...args: any[]) => PubsubBaseProtocol'.
    Construct signature return types 'Gossipsub' and 'PubsubBaseProtocol' are incompatible.
      The types of 'peers' are incompatible between these types.
        Type 'Map<string, import("/Users/alex/Documents/Workspaces/ipfs/js-ipfs/node_modules/libp2p-gossipsub/node_modules/libp2p-interfaces/dist/src/pubsub/peer-streams")>' is not assignable to type 'Map<string, import("/Users/alex/Documents/Workspaces/ipfs/js-ipfs/node_modules/libp2p-interfaces/dist/src/pubsub/peer-streams")>'.
          Type 'import("/Users/alex/Documents/Workspaces/ipfs/js-ipfs/node_modules/libp2p-gossipsub/node_modules/libp2p-interfaces/dist/src/pubsub/peer-streams")' is not assignable to type 'import("/Users/alex/Documents/Workspaces/ipfs/js-ipfs/node_modules/libp2p-interfaces/dist/src/pubsub/peer-streams")'.
            Types have separate declarations of a private property '_rawOutboundStream'.
src/runtime/libp2p-browser.js(35,7): error TS2322: Type 'typeof Gossipsub' is not assignable to type 'new (...args: any[]) => PubsubBaseProtocol'.
```

cc @vasco-santos

**Comment by vasco-santos** [comment]
`libp2p-interfaces@0.11` only added tests, I am not sure of what changed. But I can revert the commit and do a breaking change here

**Comment by achingbrain** [comment]
I think it's just because the types are loaded from different paths, same as the problem with `instanceof` and loading classes from different locations.

**Comment by vasco-santos** [comment]
I reverted with a patch and released a minor. Should be good now?

Bah, we will need to orchestrate really carefully the `libp2p-interfaces` update in `js-libp2p`

**Comment by achingbrain** [comment]
I think this sort of problem can be alleviated by exporting interfaces from `.d.ts` files and then everything depends on the interface, rather than typing an implementation and using that as argument types, etc.  This is the approach taken by [Store](https://github.com/ipfs/js-ipfs-interfaces/blob/master/packages/interface-store/src/index.d.ts#L23) in `ipfs-interfaces`.

This way at compile time TS compares the interfaces to see if there is overlap instead of checking all the fields etc of the implementation, which may be concrete types with complex field hierarchies that are unlikely to be compatible across versions.

**Comment by achingbrain** [comment]
N.b. floodsub has a similar problem but IPFS still compiles by coincidence as the default code path finds gossipsub and not floodsub.

Anyway, the patch has fixed it, thanks!
