### ISSUE TITLE
computeScore performance issue

### ISSUE THREAD

**Issue by tuyennhv** [ChainSafe/js-libp2p-gossipsub#169]
**Motivation**
+ We keep computing peer score in a lot of places without any cache
+ It's not scalable: the more messages, the more function calls we have for `computeScore()()`. When there are a lot of messages, it takes 4% cpu time of lodestar
[1130_lodestar_subscribeAllSubnets_local.cpuprofile.zip](https://github.com/ChainSafe/js-libp2p-gossipsub/files/7623357/1130_lodestar_subscribeAllSubnets_local.cpuprofile.zip)

<img width="1474" alt="Screen Shot 2021-11-30 at 13 14 38" src="https://user-images.githubusercontent.com/10568965/143995477-7cfa3cc4-8306-45bb-a10a-c669bf70f9b9.png">

**Note**
+ It's not likely it's a performance issue of `computeScore()` function itself

**Comment by dapplion** [comment]
@tuyennhv I had the same though on this, we compute the scores incredibly often. You could add some quick and dirty metrics to know how many times computeScore() is called per second
