### ISSUE TITLE
Update to `libp2p-interfaces` v4.x

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/js-libp2p-gossipsub#171]
With libp2p/js-libp2p-interfaces#111, the `libp2p-interfaces` package has now been split into _only_ containing interfaces.
The pubsub implementation is now in the `libp2p-pubsub` package.

This is a breaking change, so there will likely be some subtle incompatibilities to work through.

We should upgrade ASAP so we do not fall behind and help catch upstream issues before a lot of time has passed.

**Comment by tuyennhv** [comment]
`libp2p-interfaces` was updated to v2.0.1 https://github.com/ChainSafe/js-libp2p-gossipsub/blob/349d5a6303b9f1cd6e73819a495c1d42609bcb3f/package.json#L48, can we close this @wemeetagain ?

also `libp2p-interface` released 3.0.0 on Dec 02

**Comment by wemeetagain** [comment]
Lets update this issue to point to v3.x

**Comment by philknows** [comment]
To bump after gossipsub issues are resolved.
