### ISSUE TITLE
Re-enable unreliable tests

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/js-libp2p-gossipsub#183]
in #182 we disabled tests in `test/go-gossipsub.js` because several tests would fail in CI

We should figure our what's failing in the tests and re-enable them

**Comment by dapplion** [comment]
This seems very urgent, it's worrying that some many tests break just by changing the API to using promises

**Comment by wemeetagain** [comment]
Well this is the interesting part: they don't break locally, and they don't _always_ break in CI. And they don't always break in the same place or in the same tests.

So it seems more that the CI environment sucks and the tests are unreliable and relying on specific timing (that is the case in normal operation, but not so in sucky CI).

This is evident when the heartbeat test failed, like [here](https://github.com/ChainSafe/js-libp2p-gossipsub/runs/4674180733?check_suite_focus=true#step:6:134). A timer set for 1000ms took 1124ms to return.

**Comment by dapplion** [comment]
The danger is that a new feature PR might break something and this tests wont sound the alarm, allowing bugs to releases.

Extending the timeouts to x5 could help?
