### ISSUE TITLE
Avoid duplicate open connections

### ISSUE THREAD

**Issue by tuyennhv** [ChainSafe/js-libp2p-gossipsub#207]
**Motication**

When `doPX` (peer exchange option) is enabled, there are duplicate connections if other peers send same peer id at the same time

**Description**
To reproduce the issue, run the "test gossipsub star topology with signed peer records" test with `GossipsubPrunePeers` as 16, check connections after we do 15 heart beat

`@@@ peer 5 remote peer QmeVFBEQoZxwLuDqCiDAUqbz5BVN3Az6MLJPxDR3uKwpfV num connection 2 open,open`

**Expected**
Should not have duplicate connections to the same peer

**Comment by dapplion** [comment]
A connection is a stream, i.e. the outgoing and incoming streams or each peer should have exactly one connection that's multiplexed both ways?

**Comment by tuyennhv** [comment]
A connection contains a lot of streams, each stream could be for a specific protocol (when we use `dialProtocol`), the direction (inbound/outbound) applies for connection, not stream.

Just debug again, the connections are actually not duplicate, one for inbound and one for outbound. When we do `dialProtocol()`, libp2p uses the 1st open connection

This works as designed as libp2p accepts multiple open connections https://github.com/libp2p/js-libp2p/blob/3cfe4bbfac46dac3c7875f891909b17f39fa7c85/src/connection-manager/index.js#L308
