### ISSUE TITLE
Exports have changed between libp2p-gossipsub 0.13.0 and 0.13.2

### ISSUE THREAD

**Issue by achingbrain** [ChainSafe/js-libp2p-gossipsub#224]
libp2p-gossipsub@0.13.0 is CJS-style - https://unpkg.com/browse/libp2p-gossipsub@0.13.0/src/index.js
libp2p-gossipsub@0.13.2 is ESM-style - https://unpkg.com/browse/libp2p-gossipsub@0.13.2/src/index.js

When using `require`, `0.13.0` returns the Gossipsub impl but `0.13.2` returns an object with a property named `"default"` that is the Gossipsub impl.  `0.13.1` doesn't appear to be on npm.

This is possibly because the typescript config for the project was changed in https://github.com/ChainSafe/js-libp2p-gossipsub/pull/205

Could this change please be reverted and it go out as 0.14.0 instead?

**Comment by wemeetagain** [comment]
Should be fixed in latest version
