### ISSUE TITLE
Consider synced flow when validating gossip messages

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/js-libp2p-gossipsub#226]
**Motivation**
Right now lodestar has "StrictNoSign" signature policy, and a synced `msgIdFn`, running synced version of "handleReceivedMessage" and "validateReceivedMessage" (hard-coded in `node_modules`) gives us some improvement in a contabo machine

+ Less dropped jobs - before 40 % in average, after >20% in average
<img width="823" alt="Screen Shot 2022-04-05 at 16 13 31" src="https://user-images.githubusercontent.com/10568965/161721169-643bd244-f01d-4430-8ea6-266c80506146.png">

+ p7 is down to -337 vs consistently 0
<img width="811" alt="Screen Shot 2022-04-05 at 16 15 04" src="https://user-images.githubusercontent.com/10568965/161721414-47572d97-e74b-4fcb-9956-dff9da8c78e8.png">

+ Thanks for that "min" peer score is almost 0
<img width="814" alt="Screen Shot 2022-04-05 at 16 16 17" src="https://user-images.githubusercontent.com/10568965/161721673-3df67e52-0603-43ba-81a2-67ac20d99fc9.png">

+ We need to write a benchmark to see if it's worth to implement a "syncedHandleReceivedMessage" flag

**Comment by dapplion** [comment]
First we should quantify the cost of promises. This could lead to a lot of duplicate code and make the maintenance much more annoying. So we should have a big incentive to pursue it.

For context, validation is async because libp2p's sha256 is async. It's because they use the in-browser native crypto for browsers, which has an async API.

**Comment by philknows** [comment]
@twoeths If you still think this will give us benefits, please investigate or else we can close this.

**Comment by twoeths** [comment]
gossipsub is moved to network thread and very stable there, not worth to investigate
