### ISSUE TITLE
`opts.gossipIncoming` does nothing?

### ISSUE THREAD

**Issue by achingbrain** [ChainSafe/js-libp2p-gossipsub#231]
When it was added there was a [conditional](https://github.com/ChainSafe/js-libp2p-gossipsub/commit/325a40a6d7a440045bb4c9a7b4c781016fa975a7#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R138-R141) that checked the value of `opts.gossipIncoming` and didn't gossip incoming messages when it was `false`.

Now that this module has been refactored to not extend the base pubsub class in `@libp2p/pubsub` [nothing seems to use that init option](https://github.com/ChainSafe/js-libp2p-gossipsub/search?q=gossipIncoming).

**Comment by achingbrain** [comment]
Still does nothing AFAICS

**Comment by tuyennhv** [comment]
`gossipIncoming` option is used to forward messages to FloodSub peers and mesh peers, which is the default behavior right now.

I don't see this option in rust's implementation, @wemeetagain do we need this option for any applications? If not I think we can just delete this option.

**Comment by wemeetagain** [comment]
yeah, its stale code, should be deleted
