### ISSUE TITLE
TimeCache entries are never pruned

### ISSUE THREAD

**Issue by achingbrain** [ChainSafe/js-libp2p-gossipsub#232]
Expired entries [used to be pruned on put](https://github.com/ChainSafe/js-libp2p-gossipsub/blob/2153e68bebf7811276c4b863ffb1387236fc1e7d/ts/utils/time-cache.ts#L29) now [this doesn't happen](https://github.com/ChainSafe/js-libp2p-gossipsub/blob/master/ts/utils/time-cache.ts#L30-L32) since [the logic was revamped](https://github.com/ChainSafe/js-libp2p-gossipsub/commit/baf84f80d3aadf37005a2cfbd6afa60f85b00564#diff-8e38b9c0293607104225a1b169880d1072d258060e02fbe306b59d80f276ad22L29).

In fact the `prune()` method [doesn't seem to be invoked anywhere in the codebase](https://github.com/ChainSafe/js-libp2p-gossipsub/search?l=TypeScript&q=prune).

**Comment by dapplion** [comment]
Prune of all TimeCache structures happens here

https://github.com/ChainSafe/js-libp2p-gossipsub/blob/703ea647aaddbfc78f6d69bcd23c852a6db199a9/ts/index.ts#L2203

Current master also has metrics of the size of all data structures which show to be of stable size.

I think the Github search engine is garbage :rofl:

**Comment by achingbrain** [comment]
Hm, ok weird - I'm having problems getting the `SimpleTimeCache` tests to pass, since [this .put](https://github.com/ChainSafe/js-libp2p-gossipsub/blob/master/test/time-cache.spec.ts#L29) is what [previously caused the cache to get pruned](https://github.com/ChainSafe/js-libp2p-gossipsub/blob/2153e68bebf7811276c4b863ffb1387236fc1e7d/ts/utils/time-cache.ts#L29), from the above now I guess you'd need to do it manually after the `sandbox.clock.tick`, which isn't done in the test currently 🤷

**Comment by dapplion** [comment]
> I guess you'd need to do it manually after the sandbox.clock.tick, which isn't done in the test currently

Yes, definitely. Sorry about the test situation here. It hasn't received the care it deserve
