### ISSUE TITLE
expect(...).to.throw missing parentheses in tests

### ISSUE THREAD

**Issue by achingbrain** [ChainSafe/js-libp2p-gossipsub#233]
There are some tests that have assertions similar to:

```js
describe('TopicScoreParams validation', () => {
  it('should throw on invalid TopicScoreParams', () => {
    expect(() => validateTopicScoreParams(createTopicScoreParams({}))).to.throw
// ...
```

The tests pass, but if you change `to.throw` to `to.throw()` the tests start to fail:

```js
describe('TopicScoreParams validation', () => {
  it('should throw on invalid TopicScoreParams', () => {
    expect(() => validateTopicScoreParams(createTopicScoreParams({}))).to.throw()
// ...
```

```
  1) TopicScoreParams validation
       should throw on invalid TopicScoreParams:
     AssertionError: expected [Function] to throw an error
      at Context.<anonymous> (test/peer-score-params.spec.ts:12:80)
      at processImmediate (node:internal/timers:464:21)
```

[expect(...).to.throw()](https://www.chaijs.com/api/bdd/#method_throw) needs parentheses to work.  There are quite a few tests like this.

**Comment by dapplion** [comment]
Oh man that's so bad, is there an eslint that protects against this?

**Comment by achingbrain** [comment]
I found this by running the default linting/ts config from `aegir@37`, though I've since backed that upgrade out of my (upcoming) `@libp2p/*` migration PR because the eslint/prettier config in this repo has diverged quite far from aegir and it was causing a lot of noise in the PR.

**Comment by dapplion** [comment]
When possible I think using the same tooling and config as the rest of libp2p ecosystem is a net positive! If there are fundamental disagreements we can resolve them somewhere first
