### ISSUE TITLE
Re-enable firefox tests

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/js-libp2p-gossipsub#244]
In #236 we disabled firefox tests, which failed spuriously in CI, in order to unblock the release of js-libp2p.

We should track down the source of test flakiness and re-enable the firefox tests.

**Comment by dapplion** [comment]
has this been fixed? If so please link to PR

**Comment by mpetrunic** [comment]
https://github.com/ChainSafe/js-libp2p-gossipsub/pull/259
