### ISSUE TITLE
libp2p import for `.src/record/envelope` is deprecated 

### ISSUE THREAD

**Issue by kmkhami** [ChainSafe/js-libp2p-gossipsub#253]
When trying to upgrade libp2p from version `0.35.8` to `0.37.0` I encountered the following build error:

```
ERROR in ../zero-protocol/node_modules/libp2p-gossipsub/src/index.js 91:17-54
Module not found: Error: Package path ./src/record/envelope is not exported from package /node_modules/libp2p (see exports field in /node_modules/libp2p/package.json)
```

Does anyone know why this is occurring or have a quick fix?

**Comment by wemeetagain** [comment]
You'll need to use the package `@chainsafe/libp2p-gossipsub` with the latest version of libp2p
