### ISSUE TITLE
heartbeat performance issue

### ISSUE THREAD

**Issue by tuyennhv** [ChainSafe/js-libp2p-gossipsub#256]
**Motivation**

In a contabo node of 50 peers, `heartbeat` function may take up to 800ms - 1s which block the event loop

<img width="1249" alt="Screen Shot 2022-05-27 at 16 59 20" src="https://user-images.githubusercontent.com/10568965/170677668-aef3a8f6-13c0-4825-9933-557f816bc70a.png">

part of https://github.com/ChainSafe/lodestar/issues/4002

**Description**
- Write performance test for `heartbeat()` function
- Improve `heartbeat()` performance
- If it takes too much time, yield to event loop every x milli seconds

**Comment by dapplion** [comment]
@tuyennhv The resolution of the buckets in `gossipsub_heartbeat_duration_seconds_bucket` is really poor: [0.01, 0.1, 1]. So the quantile function can show widely inaccurate results. We should improve the bucket values and check this metric again. Since heartbeats are about 1s and we care about not looping around better bucket values would be
```
[0.01, 0.05, 0.1, 0.2, 0.4, 0.7, 1]
```
As `gossipsub_heartbeat_duration_seconds_bucket` doesn't have any labels and is called infrequently, more buckets are cheap

**Comment by dapplion** [comment]
![Screenshot from 2022-05-28 14-12-48](https://user-images.githubusercontent.com/35266934/170814886-e4310e12-f712-4af3-9b5b-09cddfd79431.png)

This chart is also a bit worrying: heartbeat should not be skipped, and should run 1/0.7 = 1.42 times / sec on average. Smooth chart below

![Screenshot from 2022-05-28 14-14-43](https://user-images.githubusercontent.com/35266934/170814970-ebf07264-3834-4ea7-a8d6-3fac89022fe8.png)

**Comment by dapplion** [comment]
The only hard data we have now is how many heartbeats take > 100ms to complete and how many take > 1000ms to complete. However you can see that many take > 100ms but almost 0 take > 1000 ms. But we don't really now the distribution between 100 and 1000 at all :shrug: 

![Screenshot from 2022-05-28 14-26-19](https://user-images.githubusercontent.com/35266934/170815377-8939ff3a-9cf5-4b7c-97dd-b0c2c9805cdb.png)
![Screenshot from 2022-05-28 14-26-36](https://user-images.githubusercontent.com/35266934/170815378-09ea3083-53fc-485d-a680-56be749f9258.png)

**Comment by tuyennhv** [comment]
with new buckets `[0.01, 0.05, 0.1, 0.2, 0.4, 0.7, 1]`, the distribution in a contabo-S (with rate interval as 5m) looks like

<img width="1221" alt="Screen Shot 2022-06-01 at 15 36 48" src="https://user-images.githubusercontent.com/10568965/171363341-8c2dfdf8-2c34-48d9-a386-e6be63c7230f.png">

**Comment by tuyennhv** [comment]
was able to catch a 775ms heartbeat, it shows that most of the time of `heartbeat()` function is due to `emitGossip()` call
<img width="1051" alt="Screen Shot 2022-06-02 at 09 49 48" src="https://user-images.githubusercontent.com/10568965/171542643-67b679b6-f704-463a-a233-30d4fac0eaf2.png">

[0522_contabo_20_subscribe_all_subnets.cpuprofile.zip](https://github.com/ChainSafe/js-libp2p-gossipsub/files/8820289/0522_contabo_20_subscribe_all_subnets.cpuprofile.zip)

right now we call `emitGossip()` 2 times in `heartbeat()` inside the fanout loop and mesh loop, and we may gossip messages to a peer twice in the same heartbeat

**Comment by dapplion** [comment]
Why is emitGossip so costly? This needs benchmark testing. emitGossip is taking 2% of total CPU time


![Screenshot from 2022-06-02 12-23-10](https://user-images.githubusercontent.com/35266934/171558617-608dbaa4-7d10-4999-a9e3-69b78845cdc3.png)

**Comment by tuyennhv** [comment]
most of the cost is for looping through topic peers

<img width="1011" alt="Screen Shot 2022-06-02 at 14 09 58" src="https://user-images.githubusercontent.com/10568965/171573564-b18b6d72-d5f4-468c-9a62-d3f23e01a8f5.png">

and for a lodestar node connecting to all attestation subnets, there are about 70 topics in total => we call `emitGossip()` ~70 times per heartbeat

**Comment by tuyennhv** [comment]
for the record, `runHeartBeat()` takes 3.6% of cpu time on a lodestar's subscribeAllSubnets node, should take another profile when all of the improvements are merged

<img width="1244" alt="Screen Shot 2022-06-15 at 10 21 05" src="https://user-images.githubusercontent.com/10568965/173729841-7602a17e-065c-4904-9a48-2c42f3493cb0.png">

[0522_contabo_20_subscribe_all_subnets.cpuprofile.zip](https://github.com/ChainSafe/js-libp2p-gossipsub/files/8905439/0522_contabo_20_subscribe_all_subnets.cpuprofile.zip)

**Comment by tuyennhv** [comment]
need to see if this still happens in the latest release (4.0.0 as of Aug 2022)

**Comment by tuyennhv** [comment]
Heartbeat duration is improved significantly (v0.14.0 vs v4.1.1)


<img width="841" alt="Screen Shot 2022-08-25 at 10 17 56" src="https://user-images.githubusercontent.com/10568965/186566662-2e10d3fb-4006-4dd1-ad3b-7fb32d694f00.png">

**Comment by tuyennhv** [comment]
This metric is incredible in v4.1.1

<img width="801" alt="Screen Shot 2022-09-28 at 09 50 12" src="https://user-images.githubusercontent.com/10568965/192676440-50506a74-9bec-4269-be54-ac8e47e25884.png">
