### ISSUE TITLE
Improve messageIdToString

### ISSUE THREAD

**Issue by tuyennhv** [ChainSafe/js-libp2p-gossipsub#269]
**Motivation**
- right now `messageIdToString` uses string concatenation which is not memory efficient and it may trigger `gc` more frequently

<img width="963" alt="Screen Shot 2022-06-08 at 11 37 56" src="https://user-images.githubusercontent.com/10568965/172532767-62620a33-b54d-4feb-94f0-0244693a61da.png">

- This was taken from a running node where it shows string concatenation
<img width="720" alt="Screen Shot 2022-06-08 at 11 34 18" src="https://user-images.githubusercontent.com/10568965/172532355-4daeeccd-72c4-4783-9e95-2c8fae6b292a.png">

see the same issue here https://github.com/ChainSafe/lodestar/issues/3446

**Description**

- we should be able to switch to `Bufffer.toString('base64')` instead
- write unit test and perf test to make sure
- should partly improve the heartbeat performance #256

**Comment by tuyennhv** [comment]
`toString(msgId, 'base64')` and `Buffer.from(data).toString('base64')` produce the same data except for the last padding character added using `Buffer.toString()`, however it's not an issue because message id is just for internal tracking and when we convert to Uint8Array, it produces the same data. @wemeetagain please help confirm if this is not correct.

**Comment by tuyennhv** [comment]
the use of `Buffer` was deprecated so not sure how can we deal with this. Do you have any ideas @wemeetagain @dapplion ?

**Comment by tuyennhv** [comment]
another example

<img width="1022" alt="Screen Shot 2022-06-09 at 10 31 00" src="https://user-images.githubusercontent.com/10568965/172758260-bdb8181e-2cd8-4347-b68d-75081b734000.png">

**Comment by dapplion** [comment]
> the use of `Buffer` was deprecated for browser compatibility so not sure how can we deal with this. Do you have any ideas @wemeetagain @dapplion ?

We can use some switching code that detects if browser or NodeJS and uses Buffer only there
