### ISSUE TITLE
libp2p:gossipsub:error createOutboundStream error TypeError: fns.shift(...) is not a function

### ISSUE THREAD

**Issue by D4nte** [ChainSafe/js-libp2p-gossipsub#305]
Getting this error message with `@chainsafe/libp2p-gossipsub@3.3.0`:

```
  libp2p:gossipsub:error createOutboundStream error TypeError: fns.shift(...) is not a function
    at rawPipe (file:///home/fryorcraken/src/status-im/js-waku/node_modules/it-pipe/src/index.ts:8:22)
    at pipe (file:///home/fryorcraken/src/status-im/js-waku/node_modules/it-pipe/src/index.ts:167:10)
    at new OutboundStream (file:///home/fryorcraken/src/status-im/js-waku/node_modules/@chainsafe/libp2p-gossipsub/src/stream.ts:22:3)
    at EventTarget.createOutboundStream (file:///home/fryorcraken/src/status-im/js-waku/node_modules/@chainsafe/libp2p-gossipsub/src/index.ts:681:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///home/fryorcraken/src/status-im/js-waku/node_modules/@chainsafe/libp2p-gossipsub/src/index.ts:486:9 +0ms
```

The issue is because the `rawStream` passed is **not** a function: https://github.com/ChainSafe/js-libp2p-gossipsub/blob/0e76f49d2924d65a6e76ecd1e842db66f2eddd34/src/index.ts#L677

Will try to investigate more later.

**Comment by D4nte** [comment]
I seemed to have fixed the issue locally by replacing

https://github.com/ChainSafe/js-libp2p-gossipsub/blob/170c1aa747937acca8d8a852495f3a6c69770ef0/src/stream.ts#L13

With `this.rawStream = rawStream.stream`. Because `rawStream` actually is:

```js
{
  stream: {
    close: [Function: close],
    closeRead: [Function: closeRead],
    closeWrite: [Function: closeWrite],
    abort: [Function: abort],
    reset: [Function: reset],
    sink: [AsyncFunction: sink],
    source: Object [AsyncGenerator] {},
    stat: { direction: 'outbound', timeline: [Object] },
    metadata: {},
    id: 'i2'
  },
  protocol: '/vac/waku/relay/2.0.0-beta2'
}
```

I know that the move of the `protocol` is a recent interface change, need to find the culprit

**Comment by wemeetagain** [comment]
Maybe due to the version of js-libp2p you're using?
Should have this integrated or else https://github.com/libp2p/js-libp2p/pull/1255/files

**Comment by D4nte** [comment]
Yes so the issue is that libp2p brings an old version of `@libp2p/connection` that implements the old API:

```
js-waku@0.24.0 /home/fryorcraken/src/status-im/js-waku
└─┬ libp2p@0.37.3
  └── @libp2p/connection@2.0.4
```

**Comment by wemeetagain** [comment]
closing this since this specific issue is resolved
