### ISSUE TITLE
Insufficient peers: how to connect peers in Gossipsub?

### ISSUE THREAD

**Issue by tmpfs** [ChainSafe/js-libp2p-gossipsub#309]
Hi, thanks for the library 🙏 

I am trying to get a basic topic publish/subscribe working using `@chainsafe/libp2p-gossipsub@3.3.0` but all the documentation I can find appears to be out of date and I am not clear how to connect the peers to the pubsub channel.

I have created a `js-libp2p` node which connects using a local `webrtc-star` and then set up the `Gossipsub` like this:

```javascript
  const host = await makeHost();    // Get our libp2p node
  await host.start();

  const pubsub = new GossipSub();
  await pubsub.init(host.components);
  await pubsub.start();

  pubsub.subscribe(topic);
```

When I try to publish I get `PublishError.InsufficientPeers` so I tried to have them dial each other in the `connect` listener:

```javascript
  host.connectionManager.addEventListener('peer:connect', async (evt) => {
    const connection = evt.detail
    const { remotePeer, remoteAddr } = connection;
    const peerId = peerIdFromString(remotePeer.toString())
    await host.peerStore.addressBook.set(peerId, [remoteAddr]);
    await host.dial(peerId);
  })
```

But I still get the `PublishError.InsufficientPeers` when I publish.

What is the correct way to connect peers with the `Gossipsub` implementation?

Thanks for any pointers!

**Comment by dapplion** [comment]
@achingbrain can you take a look?

**Comment by tmpfs** [comment]
I managed to get it working thanks 👍 I needed to assign to `pubsub` on the libp2p host and I was also affected by the bad `libp2p` published version documented here: https://github.com/libp2p/js-libp2p/issues/1306

Using the tagged version allowed me to dial peers successfully and the `GossipSub` started to work after that. Sorry for the bother.
