### ISSUE TITLE
it-pushable is not bounded, can OOM

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/js-libp2p-gossipsub#321]
- See https://github.com/alanshaw/it-pushable/issues/31

Used in

https://github.com/ChainSafe/js-libp2p-gossipsub/blob/af51f36f16dbc99d909037a40b95e034439945d8/src/stream.ts#L15

**Comment by wemeetagain** [comment]
please open an issue upstream

**Comment by mpetrunic** [comment]
You now have readableLength to check size of queue: https://github.com/alanshaw/it-pushable/pull/27

**Comment by dapplion** [comment]
> You now have readableLength to check size of queue: [alanshaw/it-pushable#27](https://github.com/alanshaw/it-pushable/pull/27)

Shouldn't this feature be part of any queue implementation? Sounds extremely basic

**Comment by wemeetagain** [comment]
The feature is there, API is such that consumer may check the property before pushing dependent on application needs.
