### ISSUE TITLE
Publish in batch

### ISSUE THREAD

**Issue by tuyennhv** [ChainSafe/js-libp2p-gossipsub#344]
**Motivation**
There is a missed attestation issue described in https://github.com/ChainSafe/lodestar/issues/4600. When lodestar wants to publish a gossip message, it wants to spread to the network asap

**Description**
Right now the steps to publish a message are as below:
- Select peers to publish, this is usually about 20 peers (as in lodestar)
- For each peer:
  - Form a new rpc for that peer with cached control messages of that peer
  - Encode message to bytes using protobuf
  - Encode to length prefix
  - Send to raw stream

The proposal is to send in batch without checking cached control messages
- Select peers to publish
- Encode messages to bytes using protobuf, then encode length prefix
- Send that bytes data to all raw stream

**Something to consider**
- Is it against the spec @wemeetagain 
- Should we add a new api or add a new flag to `publish()` method? Main thing is not to introduce a breaking change
- Does it have any side effect to control messages? Since we have to forward messages very frequently, and we also have  heartbeat, I suppose "no" optimistically

**Comment by wemeetagain** [comment]
This proposal is ok according to the spec.
Lets add a new flag to `PublishOpts`
