### ISSUE TITLE
Tag mesh peers on graft, remove tags on prune

### ISSUE THREAD

**Issue by achingbrain** [ChainSafe/js-libp2p-gossipsub#380]
To prevent the connection manager pruning connections to high-value peers, modules that need connections to certain peers should tag them to ensure they don't get culled by the connection manager when connection limits have been specified and reached.

When this module grafts mesh peers for a given topic, it should use the [peerStore.tagPeer](https://github.com/libp2p/js-libp2p-interfaces/blob/master/packages/interface-peer-store/src/index.ts#L255) method to tag them with a value:

```js
libp2p.peerStore.tagPeer(peerId, 'gossipsub-mesh-peer', {
  value: 100 // value should be 0-100
})
```

When they are pruned from a mesh [peerStore.unTagPeer](https://github.com/libp2p/js-libp2p-interfaces/blob/master/packages/interface-peer-store/src/index.ts#L256) should be used:

```js
libp2p.peerStore.unTagPeer(peerId, 'gossipsub-mesh-peer')
```

Refs: https://github.com/libp2p/js-libp2p/issues/369

**Comment by dapplion** [comment]
Do other implementations have this feature? I don't recall seeing it. Speaking for Lodestar we have more complex logic to decide the value of the peer so this feature won't be useful at all.

**Comment by achingbrain** [comment]
> Do other implementations have this feature? I don't recall seeing it.

See the referenced issue in the OP for context.

> Speaking for Lodestar we have more complex logic to decide the value of the peer 

If that's the case lodestar may wish to tag high value peers as well.

**Comment by dapplion** [comment]
> If that's the case lodestar may wish to tag high value peers as well.

If I understand this feature is relevant because the connection manager may choose to disconnect peers at will right? Can consumers completely disable that so peer management is done 100% by the consumer?

**Comment by achingbrain** [comment]
Yes, just leave `maxConnections` as the default (`Infinity`).
