### ISSUE TITLE
Add logger option

### ISSUE THREAD

**Issue by tuyennhv** [ChainSafe/js-libp2p-gossipsub#406]
**Motivation**
Right now Lodestar uses `js-libp2p-gossipsub` but there is no way to incorporate gossipsub log into Lodestar's log which make it hard to debug

**Description**
- Right now `js-libp2p-gossipsub` uses this log https://www.npmjs.com/package/debug#output-streams
- Would be great if it has a logger option following an interface so that application can go with its own log, if not then fallback to a default logger

**Comment by dapplion** [comment]
@tuyennhv to enable gossipsub's logger you need to run lodestar with an ENV variable like `DEBUG=libp2p:gossipsub` such that

```
DEBUG=libp2p:gossipsub node lodestar.js
```

**Comment by tuyennhv** [comment]
> @tuyennhv to enable gossipsub's logger you need to run lodestar with an ENV variable like `DEBUG=libp2p:gossipsub:*` such that
> 
> ```
> DEBUG=libp2p:gossipsub:* node lodestar.js
> ```

@dapplion yeah that's what I did, I successfully incorporated gossipsub logs into lodestar's log files in my branch
