### ISSUE TITLE
Export Metrics 

### ISSUE THREAD

**Issue by maschad** [ChainSafe/js-libp2p-gossipsub#414]
Done Criteria
Export metrics leveraging the work done in https://github.com/libp2p/js-libp2p/issues/1458

Motivation
Better observability for performance and benchmarking. See: https://github.com/libp2p/js-libp2p/issues/1458#issuecomment-1323833476

**Comment by wemeetagain** [comment]
Closing this issue since this library contains many metrics already.
A nice enhancement would be to revisit the exact implementation and make it more standardized with the rest of the js-libp2p ecosystem.
