### ISSUE TITLE
TypeError when setting direct peers in @chainsafe/libp2p-gossipsub with new libp2p peerStore structure

### ISSUE THREAD

**Issue by kostysh** [ChainSafe/js-libp2p-gossipsub#427]
I an using `@chainsafe/libp2p-gossipsub` version `7.0.0` and `libp2p` version `0.45.0` on Linux, node.js v18.

Steps to reproduce:
1. Define `directPeers` in the `libp2p` options object.
2. Start `libp2p` node with `@chainsafe/libp2p-gossipsub` protocol.
3. Observe the following error:
 
```
TypeError: Cannot read properties of undefined (reading 'add')
    at file:///.../node_modules/@chainsafe/libp2p-gossipsub/src/index.ts:549:53
```

Details: 
The error occurs during the try to set direct peer addresses in the `addressBook` (https://github.com/ChainSafe/js-libp2p-gossipsub/blob/f62859b346474ff3e29d59e31449b15d60e054d6/src/index.ts#L553). 
It seems that the new version of the `libp2p` has a different `peerStore` structure.

**Comment by maschad** [comment]
Sorry the inconvenience but libp2p 0.45.0 introduced some [breaking changes](https://github.com/libp2p/js-libp2p/releases/tag/v0.45.0) which have been addressed in #425 , so the next  _gossipsub_  release  should include this [fix](https://github.com/ChainSafe/js-libp2p-gossipsub/pull/425/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R552-R554).
