### ISSUE TITLE
`GossipFactor` is not configurable

### ISSUE THREAD

**Issue by mkermani144** [ChainSafe/js-libp2p-gossipsub#501]
Based on [the spec](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#overview-of-new-parameters), the `GossipFactor` is a configurable parameter with a reasonable default of `0.25`. But in the current implementation, it is supposed that it's a constant.  
What is the reason the team didn't include it in the options, like other params such as `FloodPublish` or `PruneBackoff`?

**Comment by wemeetagain** [comment]
Its just an oversight on our part, it should be configurable

**Comment by mkermani144** [comment]
@wemeetagain
Thanks for the quick reply!  
How can I help? If it's as simple as adding it to opts, defaulting it to existing `0.25` constant, and switching the usage from the constant to the opt, I may be able to open a PR. I don't know anything about your tests, though.

**Comment by wemeetagain** [comment]
Go for it. You should be able to use the existing configurable params as an example.

Don't worry about adding a test, at a later time, we could (debatably should) add config validation (and tests) for all configurable params.
