### ISSUE TITLE
v14.0.1 incompatible with latest libp2p libs bump

### ISSUE THREAD

**Issue by d-roak** [ChainSafe/js-libp2p-gossipsub#509]
Main reason seems to be peer-collections version mismatch from `6.0.2` with `6.0.6`

<img width="1548" alt="image" src="https://github.com/user-attachments/assets/3afe8d70-9046-47e4-bcbf-ef484aaeb61b">

<img width="385" alt="image" src="https://github.com/user-attachments/assets/5fc27108-cb77-4ed4-b8d2-b21c7e515d9d">

**Comment by achingbrain** [comment]
These are all in-range semver updates - you may need to re-create your lockfile?

**Comment by d-roak** [comment]
worked, awesome. TIL something new 
Thank you very much !

**Comment by d-roak** [comment]
@achingbrain  actually, it was not solved. It was working locally, but failing to build on the CI, after deleting the `node_modules` and installing every dep and build it from scratch, it fails exactly with the same error

**Comment by achingbrain** [comment]
You likely still have incorrect dependency versions installed.  If you look in `node_modules/.pnpm` you may see lots of different-yet-semver compatible versions of the deps in question.

I checked the branch out from https://github.com/topology-foundation/ts-topology/pull/193 - it looks like you're using `pnpm`.

You need to delete your lockfile and reinstall with [resolution-mode = highest](https://pnpm.io/npmrc#resolution-mode) in your `.npmrc` to get `pnpm` to respect semver.

Reinstalling after this should take the updated lockfile.

**Comment by d-roak** [comment]
thank you so much for going the extra mile to help us!
