### ISSUE TITLE
Naming of the repo

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/js-libp2p-gossipsub#76]
This repo is named `gossipsub-js` rather than the more standard `js-libp2p-gossipsub`.

It would be nice to conform to the naming of all of the other libp2p repos.
Perhaps we should id all known links that would need to be updated if we updated the repo name here.

**Comment by vasco-santos** [comment]
Totally agree on this. I think that github keeps the old url, at least for a while. But, we should update them if possible.

I am aware on these:

 `libp2p/js-libp2p`
- [ ] https://github.com/libp2p/js-libp2p/blob/98626530516f6c5872813ee6d55dab0529695caa/README.md#packages
- [ ] https://github.com/libp2p/js-libp2p/blob/master/doc/CONFIGURATION.md#pubsub
- [ ] https://github.com/libp2p/js-libp2p/blob/29a96690ad1cfb27373e798d42cc11bacbd9be33/examples/pubsub/README.md#publish-subscribe

 `libp2p/js-libp2p-pubsub`
- [ ] https://github.com/libp2p/js-libp2p-pubsub#implementations-using-this-base-protocol

`libp2p/specs`
- [ ] https://github.com/libp2p/specs/tree/master/pubsub/gossipsub#implementation-status

**Comment by wemeetagain** [comment]
Updated! PRs in progress for the above three repos:
https://github.com/libp2p/js-libp2p/pull/648
https://github.com/libp2p/js-libp2p-pubsub
https://github.com/libp2p/specs

**Comment by wemeetagain** [comment]
closing this issue, `gossipsub-js` is dead, long live `js-libp2p-gossipsub`

feel free to reopen or comment if any additional `gossipsub-js` references are found
