### ISSUE TITLE
Releasing via Aegir

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/js-libp2p-gossipsub#80]
Unfortunately, didn't test out releasing w/ Aegir in #77 
There are a few issues with the current setup when trying to release with Aegir
1. `.eslint.js` getting picked up by aegir for its linting step. Can be mitigated by either running with `--lint=false` or renaming `.eslint.js` to eg: `.eslint.ts.js`
2. `tsc` never gets run during the release cycle, so aegir fails on the test and other steps. Can be mitigated by either checking in built js in `src/` or adding a tsc step in aegir

**Comment by vasco-santos** [comment]
1. we can do --lint=false and add a prerelease with lint?

2. should we also add `tsc`to prerelease?

what do you think?

**Comment by wemeetagain** [comment]
1. sounds good

2. aegir treats this as a 'dirty repo' since the src files aren't checked in

**Comment by vasco-santos** [comment]
Humm, skipping the `dirty repo` for now would be the best approach, I think. Aegir should not support it, but it should be easy to add.
Checking the `src` seems strange and might create confusion for other contributors.

What do you think? Maybe you can open an issue in `aegir` to discuss it first? Meanwhile, I can release this with a custom aegir to avoid the dirty repo thing

**Comment by mpetrunic** [comment]
Maybe we can fork aegir and rename to aegir-ts where we would adjust tools to expect ts. Later on upstream to aegir - - ts flag or something. We could you custom aegir in noise repo (we have custom scripts and lint there)

**Comment by wemeetagain** [comment]
Yeah, checking in src/ probably causes more problems than we want.

:+1: on releasing w a custom aegir for now.

I think ideally, aegir could have extensions for typescript projects. Add a 'compile' step that could be flagged. I can envision a --ts flag that augments linting, releasing, building, etc to support our (or a similar) flow.
@mpetrunic I think we're thinking along the same lines

**Comment by vasco-santos** [comment]
@mpetrunic I am ok with that. But, I would recommend creating an issue in `aegir` to get this discussed

**Comment by mpetrunic** [comment]
unstale
